### ISSUE TITLE
Upgrade to AutoMapper 5.0.2 issue

### ISSUE THREAD

**Issue by dmdymov** [TylerCarlson1/Automapper.Collection#18]
I'm trying to upgrade my project from AutoMapper 4.1.1 / AutoMapper.Collection 1.1.2 to AutoMapper 5.0.2 / AutoMapper.Collection 2.0.1. I have a scenario which works fine with old dlls and I get unexpected null as a result of mapping with new dlls.

[Gist with issue code.](https://gist.github.com/dmdymov/d94a094be72c86fc64b1ceb91ac65673)

Is this a bug  or  I am missing something?

**Comment by TylerCarlson1** [comment]
I think this is a bug with AutoMapper 5.0.2 and you need to upgrade that.  When source or destination are null it defaults back to the CollectionMapper in AutoMapper to do the mapping.

I know Collection mapping has been updated recently in AutoMapper.

**Comment by dmdymov** [comment]
For the latest AutoMapper 5.1.1:

System.MethodAccessException at Mapper.Initialize:
"AutoMapper.Mappers.EquivlentExpressionAddRemoveCollectionMapper.IsMatch(AutoMapper.TypePair)" couldn't get access to "AutoMapper.Configuration.PrimitiveExtensions.IsEnumerableType(System.Type)"

Any thoughts on this?

**Comment by TylerCarlson1** [comment]
Now THAT is a bug that I need to fix.

I'll try to make a build that fixes it that works in 5.1.1 by the end of the week.

**Comment by TylerCarlson1** [comment]
2.1.0 Should fix this issue.

Removed as much of AutoMapper's internal code I was using before, so hopefully only refactors of the API will only require updates.

**Comment by dmdymov** [comment]
Yes, there's no exception with 2.1.0. But null as a result of mapping is still there. I think I'll try to create an Automapper issue.

**Comment by dmdymov** [comment]
I am here again. [AutoMapper issue](https://github.com/AutoMapper/AutoMapper/issues/1729).

@lbargaoanu :

> Then I guess @TylerCarlson1 should help you here.

What should I do know? This is getting weird a bit.

**Comment by TylerCarlson1** [comment]
I'll have to look into it some more then.

**Comment by TylerCarlson1** [comment]
Yea when updating the logic changed and the null check changed and caused the functionality to break for nulls.

**Comment by TylerCarlson1** [comment]
2.1.1 should fix the original issue.  Wrote unit tests for it.

**Comment by dmdymov** [comment]
Everything is OK now, thank you.
