### ISSUE TITLE
it does not work as expected!

### ISSUE THREAD

**Issue by askdong** [TylerCarlson1/Automapper.Collection#8]
Dear TylerCarlson,

Could you take time to look below simple example?
I want update exist blog with late-added post, since the exist blog already has 2 posts, and new blog has 1 post, so I expected the updated exist blog should has 3 posts, but it did not happen.

thank you very much!

using AutoMapper;
using AutoMapper.EquivilencyExpression;
using AutoMapper.Mappers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnitTest
{

    public class Blog 
    {
        public Blog()
        {
            LstPost = new List<Post>();
        }
        public int BlogId { get; set; }
        public string BlogUrl { get; set; }
        public List<Post> LstPost { get; set; }
    }

  
    public class Post
    {
        public int PostId { get; set; }
        public string PostTitle { get; set; }
        public string Content { get; set; }
    }

    [TestClass]
    public class AutoMapCollection
    {

        private IMapper CreateMapper()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<CollectionProfile>();
                cfg.CreateMap<Post, Post>().EqualityComparision((n, o) => n.PostId == o.PostId);
                cfg.CreateMap<Blog, Blog>();

            });

            return config.CreateMapper();
        }

        [TestMethod]
        public void AddPostToBlog()
        {           
            var existBlog = new Blog();
            existBlog.BlogId = 1;
            existBlog.BlogUrl = "blog url";

            var post1 = new Post() { PostId = 1, PostTitle = "post1" };
            var post2 = new Post() { PostId = 2, PostTitle = "post2" };

            existBlog.LstPost.Add(post1);
            existBlog.LstPost.Add(post2);

            var newBlog = new Blog();
            newBlog.BlogId = 1;
            newBlog.BlogUrl = "updated url";

            var post3 = new Post() { PostId = 3, PostTitle = "post3" };
            newBlog.LstPost.Add(post3);

            var mapper = CreateMapper();

            mapper.Map<Blog, Blog>(newBlog, existBlog);

            Assert.AreEqual(3, existBlog.LstPost.Count);
        }
    }
}

**Comment by TylerCarlson1** [comment]
AutoMapper isn't meant to clone objects.  If you did something like Blog to BlogDTO and Post to PostDTO it would work.  If you are using the exact same types it doesn't map as expected, even without AutoMapper.Collection.

**Comment by askdong** [comment]
it's not about cloning.  I want to update the exist object with another instance of the same type :)

**Comment by askdong** [comment]
I make sure that simple objects(no collection child propery) with same type can map as expected with AutoMapper,  I expected that AutoMapper.Collection also can work, that will be awesome!

**Comment by TylerCarlson1** [comment]
If you remove `.EqualityComparision((n, o) => n.PostId == o.PostId)` and the test still fails, then there's nothing I can really do.  Cause without that it will use AutoMapper's default collection logic, and if that doesn't work then mine won't work as well.

I think what happens if it's the same type, it will just use the destination value and not do the mapping, or something along these lines.  AutoMapper doesn't support these kinds of scenarios in general.

**Comment by askdong** [comment]
Dear TylerCarlson,
It was my misunderstanding, the collection works as my expected!
sorry for this stupid question!
